/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-10 14:50:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link rel=\"icon\" href=\"imgs/icon.png\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\n");
      out.write("<title> Tweetako </title>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://kit.fontawesome.com/fff54109b4.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"//fonts.googleapis.com/css?family=Open+Sans\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function(){\n");
      out.write("	\n");
      out.write("	$.ajaxSetup({ cache: false }); //Avoids Internet Explorer caching!	\n");
      out.write("	\n");
      out.write("	$(document).on(\"click\",\".menu\",function(event) {\n");
      out.write("		$('#content').load($(this).attr('id'));\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	$(document).on(\"submit\",\"form\", function(event) {\n");
      out.write("		\n");
      out.write("		var form = this;\n");
      out.write("		var data = new FormData(form);\n");
      out.write("		\n");
      out.write("		$.ajax( {\n");
      out.write("		  type: 'POST',\n");
      out.write("		  enctype: 'multipart/form-data',\n");
      out.write("	      url: $(form).attr('action'),\n");
      out.write("	      data: data,\n");
      out.write("	      processData: false,\n");
      out.write("	      contentType: false\n");
      out.write("		}).done(function(html){\n");
      out.write("			$(\"#content\").html(html);\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	// Edit Profile\n");
      out.write("	$(document).on(\"click\",\".editUser\",function(event) {\n");
      out.write("			$(\"#content\").load(\"EditProfileController\",$(this).serialize());\n");
      out.write("			event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Search users */\n");
      out.write("	$(document).on(\"click\",\"#searchUsers\",function(event){\n");
      out.write("		$(\"#content\").load(\"SearchUsers\", { Searchcontent: $(\"#UsersContentSearch\").text()});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Add tweet */\n");
      out.write("	$(document).on(\"click\",\"#addTweet\",function(event){\n");
      out.write("		$.post( \"AddTweet\", { content: $(\"#tweetContent\").text()}, function(event) {\n");
      out.write("			$(\"#content\").load(\"GetOwnTimeline\");		\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Comment tweet */\n");
      out.write("	$(document).on(\"click\",\"#CommentTweet\",function(event){\n");
      out.write("		var x = $(this).parent().attr(\"id\");\n");
      out.write("		$.post( \"CommentTweet\", { content: $(\"#tweetComment\").text(), pid: x }, function(event) {\n");
      out.write("			$(\"#content\").load(\"TweetCompleteController\", { id: x });	\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Edit tweet */\n");
      out.write("	$(document).on(\"click\",\".editTweet\",function(event){\n");
      out.write("		$.post( \"EditTweet\", { id: $(this).parent().parent().parent().attr(\"id\"), content: $(this).parent().children(\"#NewTweetContent\").text()}, function(event) {\n");
      out.write("			$(\"#content\").load(\"GetOwnTimeline\");		\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Edit tweet Profile*/\n");
      out.write("	$(document).on(\"click\",\".editTweetProfile\",function(event){\n");
      out.write("		var x = $(this).attr(\"id\");\n");
      out.write("		$.post( \"EditTweet\", { id: $(this).parent().parent().parent().attr(\"id\"), content: $(this).parent().children(\"#NewTweetContent\").text()}, function(event) {\n");
      out.write("			$(\"#content\").load(\"GetUserProfileController\", { id: x });	\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	/* Edit tweet Commet*/\n");
      out.write("	$(document).on(\"click\",\".editTweetComment\",function(event){\n");
      out.write("		var x = $(this).attr(\"id\");\n");
      out.write("		$.post( \"EditTweet\", { id: $(this).parent().parent().parent().attr(\"id\"), content: $(this).parent().children(\"#NewTweetContent\").text()}, function(event) {\n");
      out.write("			$(\"#content\").load(\"TweetCompleteController\", { id: x });	\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	/* Delete tweet */\n");
      out.write("	$(document).on(\"click\",\".delTweet\",function(event){\n");
      out.write("		var tweet = $(this).parent();\n");
      out.write("		$.post( \"DelTweet\", { id: $(this).parent().parent().parent().attr(\"id\") } , function(event) {\n");
      out.write("			$(\"#content\").load(\"GetOwnTimeline\");				\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	/* Delete tweet Profile*/\n");
      out.write("	$(document).on(\"click\",\".delTweetProfile\",function(event){\n");
      out.write("		var tweet = $(this).parent();\n");
      out.write("		var x = $(this).attr(\"id\");\n");
      out.write("		$.post( \"DelTweet\", { id: $(this).parent().parent().parent().attr(\"id\") } , function(event) {\n");
      out.write("			$(\"#content\").load(\"GetUserProfileController\", { id: x });			\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	/* Delete tweet Comment*/\n");
      out.write("	$(document).on(\"click\",\".delTweetComment\",function(event){\n");
      out.write("		var tweet = $(this).parent();\n");
      out.write("		var x = $(this).attr(\"id\");\n");
      out.write("		$.post( \"DelTweet\", { id: $(this).parent().parent().parent().attr(\"id\") } , function(event) {\n");
      out.write("			$(\"#content\").load(\"TweetCompleteController\", { id: x });			\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	/* Like tweet */\n");
      out.write("	$(document).on(\"click\",\".likeTweet\",function(event){\n");
      out.write("		var tweet = $(this).parent();\n");
      out.write("		$.post( \"LikeTweet\", { id: $(this).parent().parent().parent().attr(\"id\") } , function(event) {\n");
      out.write("			$(\"#content\").load(\"GetOwnTimeline\");				\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* DisLike tweet */\n");
      out.write("	$(document).on(\"click\",\".dislikeTweet\",function(event){\n");
      out.write("		var tweet = $(this).parent();\n");
      out.write("		$.post( \"DislikeTweet\", { id: $(this).parent().parent().parent().attr(\"id\") } , function(event) {\n");
      out.write("			$(\"#content\").load(\"GetOwnTimeline\");				\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Like tweet Profile */\n");
      out.write("	$(document).on(\"click\",\".likeTweetProfile\",function(event){\n");
      out.write("		var tweet = $(this).parent();\n");
      out.write("		var x = $(this).attr(\"id\");\n");
      out.write("\n");
      out.write("		$.post( \"LikeTweet\", { id: $(this).parent().parent().parent().attr(\"id\") } , function(event) {\n");
      out.write("			$(\"#content\").load(\"GetUserProfileController\", { id: x });\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* DisLike tweet Profile*/\n");
      out.write("	$(document).on(\"click\",\".dislikeTweetProfile\",function(event){\n");
      out.write("		var tweet = $(this).parent();\n");
      out.write("		var x = $(this).attr(\"id\");\n");
      out.write("\n");
      out.write("		$.post( \"DislikeTweet\", { id: $(this).parent().parent().parent().attr(\"id\") } , function(event) {\n");
      out.write("			$(\"#content\").load(\"GetUserProfileController\", { id: x });\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Like tweet Comment */\n");
      out.write("	$(document).on(\"click\",\".likeTweetComment\",function(event){\n");
      out.write("		var tweet = $(this).parent();\n");
      out.write("		var x = $(this).attr(\"id\");\n");
      out.write("\n");
      out.write("		$.post( \"LikeTweet\", { id: $(this).parent().parent().parent().attr(\"id\") } , function(event) {\n");
      out.write("			$(\"#content\").load(\"TweetCompleteController\", { id: x });\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* DisLike tweet Comment*/\n");
      out.write("	$(document).on(\"click\",\".dislikeTweetComment\",function(event){\n");
      out.write("		var tweet = $(this).parent();\n");
      out.write("		var x = $(this).attr(\"id\");\n");
      out.write("\n");
      out.write("		$.post( \"DislikeTweet\", { id: $(this).parent().parent().parent().attr(\"id\") } , function(event) {\n");
      out.write("			$(\"#content\").load(\"TweetCompleteController\", { id: x });\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Follow user */\n");
      out.write("	$(document).on(\"click\",\".followUser\",function(event){\n");
      out.write("		var user = $(this).parent();\n");
      out.write("		$.post( \"FollowUser\", { id: $(this).parent().attr(\"id\") }, function(event) { \n");
      out.write("			$(\"#content\").load(\"GetFollowedUsers\");\n");
      out.write("			$(\"#lcolumn\").load(\"GetNotFollowedUsers\");\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	/* UnFollow user */\n");
      out.write("	$(document).on(\"click\",\".unfollowUser\",function(event) {\n");
      out.write("		var user = $(this).parent();\n");
      out.write("		$.post( \"UnFollowUser\", { id: $(this).parent().attr(\"id\") }, function(event) {\n");
      out.write("			$(\"#content\").load(\"GetFollowedUsers\");\n");
      out.write("			$(\"#lcolumn\").load(\"GetNotFollowedUsers\");\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Go to fuser profile */\n");
      out.write("	$(document).on(\"click\",\".fuserInfo\",function(event) {\n");
      out.write("		var user = $(this).parent();\n");
      out.write("		$(\"#content\").load(\"GetUserProfileController\", { id: $(this).parent().attr(\"id\") });\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	/* Go to user tweet profile*/\n");
      out.write("	$(document).on(\"click\",\".tweetUserProfile\",function(event) {\n");
      out.write("		var user = $(this).parent();\n");
      out.write("		$(\"#content\").load(\"GetUserProfileController\", { id: $(this).attr(\"id\") });\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Delete account */\n");
      out.write("	$(document).on(\"click\",\".DeleteAccount\",function(event) {\n");
      out.write("		$.post( \"DelUser\", { id: $(this).attr(\"id\")}, function(event) {\n");
      out.write("			$(\"#content\").load(\"GetOwnTimeline\");	\n");
      out.write("		});\n");
      out.write("		event.preventDefault();\n");
      out.write("		\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	/* Complete tweet*/\n");
      out.write("	$(document).on(\"click\",\"div.tweet\",function(event) {\n");
      out.write("		//alert(\"hola\");\n");
      out.write("		$(\"#content\").load(\"TweetCompleteController\", { id: $(this).attr(\"id\") });\n");
      out.write("		event.preventDefault();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$(document).on(\"click\",\"div.tweet button.likeTweet\",function(event) {\n");
      out.write("		event.stopPropagation();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$(document).on(\"click\",\"div.tweet button.dislikeTweet\",function(event) {\n");
      out.write("		event.stopPropagation();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$(document).on(\"click\",\"div.tweet button.editButton\",function(event) {\n");
      out.write("		event.stopPropagation();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$(document).on(\"click\",\"div.tweet button.delTweet\",function(event) {\n");
      out.write("		event.stopPropagation();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$(document).on(\"click\",\"div.tweet button.editTweet\",function(event) {\n");
      out.write("		event.stopPropagation();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$(document).on(\"click\",\"div.tweet button.cancelButton\",function(event) {\n");
      out.write("		event.stopPropagation();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$(document).on(\"click\",\"div.tweet p.p-editable\",function(event) {\n");
      out.write("		event.stopPropagation();\n");
      out.write("	});\n");
      out.write("		\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write(" 	<!-- Begin Navigation -->\n");
      out.write(" 	<div id=\"navigation\">\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\n");
      out.write(" 	</div>\n");
      out.write(" 	<!-- End Navigation -->\n");
      out.write(" \n");
      out.write(" 	<!-- Begin Content -->\n");
      out.write("	<div class=\"generalContent\">\n");
      out.write(" 	<!-- Left Column -->\n");
      out.write("	<div class=\"container col-lateral content-pading col-hide-small\">\n");
      out.write("		<div id=\"rcolumn\">\n");
      out.write("			<p></p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Middle Column -->	\n");
      out.write("	<div class=\"col-central content-pading\">\n");
      out.write("		<div id=\"content\">\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- Right Column -->\n");
      out.write("	<div class=\"container col-lateral content-pading col-hide-small\">\n");
      out.write("		<div id=\"lcolumn\">\n");
      out.write("			<p></p>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- End Content -->\n");
      out.write("	<!-- Footer -->\n");
      out.write("	\n");
      out.write("	<script>\n");
      out.write("		function stack() {\n");
      out.write("  			var x = document.getElementById(\"stack\");\n");
      out.write("  			if (x.className.indexOf(\"show\") == -1) {\n");
      out.write("    			x.className += \" show\";\n");
      out.write("  			} else { \n");
      out.write("    		x.className = x.className.replace(\" show\", \"\");\n");
      out.write("  			}\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
